
name: Liquibase Url Prerequisites Check

# Job will run nightly at 02:10 EDT / 01:10 CDT
# Time below is UTC
on:
  schedule:
    - cron: "10 6 * * *"
  workflow_dispatch:

jobs:
  urlcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check URLs
        uses: urlstechie/urlchecker-action@master
        with:
          # A comma-separated list of file types to cover in the URL checks
          include_files: url-test.md
          # Choose whether to include file with no URLs in the printouts.
          print_all: false
          # Choose whether to print a more verbose end summary with files and broken URLs.
          verbose: true
          # The timeout seconds to provide to requests, defaults to 5 seconds
          timeout: 5
          # How many times to retry a failed request (each is logged, defaults to 1)
          retry_count: 2
          # choose if the force pass or not
          force_pass : false
